// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.1
// source: discovery.proto

package pqproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Service       []string               `protobuf:"bytes,2,rep,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *ListEndpointsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ListEndpointsRequest) GetService() []string {
	if x != nil {
		return x.Service
	}
	return nil
}

type EndpointInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Address               string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port                  uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	LoadFactor            float32                `protobuf:"fixed32,3,opt,name=load_factor,json=loadFactor,proto3" json:"load_factor,omitempty"`
	Ssl                   bool                   `protobuf:"varint,4,opt,name=ssl,proto3" json:"ssl,omitempty"`
	Service               []string               `protobuf:"bytes,5,rep,name=service,proto3" json:"service,omitempty"`
	Location              string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	NodeId                uint32                 `protobuf:"varint,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IpV4                  []string               `protobuf:"bytes,8,rep,name=ip_v4,json=ipV4,proto3" json:"ip_v4,omitempty"`
	IpV6                  []string               `protobuf:"bytes,9,rep,name=ip_v6,json=ipV6,proto3" json:"ip_v6,omitempty"`
	SslTargetNameOverride string                 `protobuf:"bytes,10,opt,name=ssl_target_name_override,json=sslTargetNameOverride,proto3" json:"ssl_target_name_override,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EndpointInfo) Reset() {
	*x = EndpointInfo{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointInfo) ProtoMessage() {}

func (x *EndpointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointInfo.ProtoReflect.Descriptor instead.
func (*EndpointInfo) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EndpointInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EndpointInfo) GetLoadFactor() float32 {
	if x != nil {
		return x.LoadFactor
	}
	return 0
}

func (x *EndpointInfo) GetSsl() bool {
	if x != nil {
		return x.Ssl
	}
	return false
}

func (x *EndpointInfo) GetService() []string {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *EndpointInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EndpointInfo) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *EndpointInfo) GetIpV4() []string {
	if x != nil {
		return x.IpV4
	}
	return nil
}

func (x *EndpointInfo) GetIpV6() []string {
	if x != nil {
		return x.IpV6
	}
	return nil
}

func (x *EndpointInfo) GetSslTargetNameOverride() string {
	if x != nil {
		return x.SslTargetNameOverride
	}
	return ""
}

type ListEndpointsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointInfo        `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	SelfLocation  string                 `protobuf:"bytes,2,opt,name=self_location,json=selfLocation,proto3" json:"self_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResult) Reset() {
	*x = ListEndpointsResult{}
	mi := &file_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResult) ProtoMessage() {}

func (x *ListEndpointsResult) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResult.ProtoReflect.Descriptor instead.
func (*ListEndpointsResult) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *ListEndpointsResult) GetEndpoints() []*EndpointInfo {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ListEndpointsResult) GetSelfLocation() string {
	if x != nil {
		return x.SelfLocation
	}
	return ""
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Status        int64                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Result        *anypb.Any             `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Operation) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Operation) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *ListEndpointsResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\x10Ydb.Discovery.V1\x1a\x19google/protobuf/any.proto\"L\n" +
	"\x14ListEndpointsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x18\n" +
	"\aservice\x18\x02 \x03(\tR\aservice\"\xa1\x02\n" +
	"\fEndpointInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1f\n" +
	"\vload_factor\x18\x03 \x01(\x02R\n" +
	"loadFactor\x12\x10\n" +
	"\x03ssl\x18\x04 \x01(\bR\x03ssl\x12\x18\n" +
	"\aservice\x18\x05 \x03(\tR\aservice\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x17\n" +
	"\anode_id\x18\a \x01(\rR\x06nodeId\x12\x13\n" +
	"\x05ip_v4\x18\b \x03(\tR\x04ipV4\x12\x13\n" +
	"\x05ip_v6\x18\t \x03(\tR\x04ipV6\x127\n" +
	"\x18ssl_target_name_override\x18\n" +
	" \x01(\tR\x15sslTargetNameOverride\"x\n" +
	"\x13ListEndpointsResult\x12<\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1e.Ydb.Discovery.V1.EndpointInfoR\tendpoints\x12#\n" +
	"\rself_location\x18\x02 \x01(\tR\fselfLocation\"w\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x03R\x06status\x12,\n" +
	"\x06result\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x06result\"R\n" +
	"\x15ListEndpointsResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.Ydb.Discovery.V1.OperationR\toperation2t\n" +
	"\x10DiscoveryService\x12`\n" +
	"\rListEndpoints\x12&.Ydb.Discovery.V1.ListEndpointsRequest\x1a'.Ydb.Discovery.V1.ListEndpointsResponseB)Z'transferia2-go/internal/pqproto;pqprotob\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_discovery_proto_goTypes = []any{
	(*ListEndpointsRequest)(nil),  // 0: Ydb.Discovery.V1.ListEndpointsRequest
	(*EndpointInfo)(nil),          // 1: Ydb.Discovery.V1.EndpointInfo
	(*ListEndpointsResult)(nil),   // 2: Ydb.Discovery.V1.ListEndpointsResult
	(*Operation)(nil),             // 3: Ydb.Discovery.V1.Operation
	(*ListEndpointsResponse)(nil), // 4: Ydb.Discovery.V1.ListEndpointsResponse
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_discovery_proto_depIdxs = []int32{
	1, // 0: Ydb.Discovery.V1.ListEndpointsResult.endpoints:type_name -> Ydb.Discovery.V1.EndpointInfo
	5, // 1: Ydb.Discovery.V1.Operation.result:type_name -> google.protobuf.Any
	3, // 2: Ydb.Discovery.V1.ListEndpointsResponse.operation:type_name -> Ydb.Discovery.V1.Operation
	0, // 3: Ydb.Discovery.V1.DiscoveryService.ListEndpoints:input_type -> Ydb.Discovery.V1.ListEndpointsRequest
	4, // 4: Ydb.Discovery.V1.DiscoveryService.ListEndpoints:output_type -> Ydb.Discovery.V1.ListEndpointsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
