// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.1
// source: persqueue.proto

package pqproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Codec int32

const (
	Codec_CODEC_UNSPECIFIED Codec = 0
	Codec_CODEC_RAW         Codec = 1
	Codec_CODEC_GZIP        Codec = 2
	Codec_CODEC_LZOP        Codec = 3
	Codec_CODEC_ZSTD        Codec = 4
)

// Enum value maps for Codec.
var (
	Codec_name = map[int32]string{
		0: "CODEC_UNSPECIFIED",
		1: "CODEC_RAW",
		2: "CODEC_GZIP",
		3: "CODEC_LZOP",
		4: "CODEC_ZSTD",
	}
	Codec_value = map[string]int32{
		"CODEC_UNSPECIFIED": 0,
		"CODEC_RAW":         1,
		"CODEC_GZIP":        2,
		"CODEC_LZOP":        3,
		"CODEC_ZSTD":        4,
	}
)

func (x Codec) Enum() *Codec {
	p := new(Codec)
	*p = x
	return p
}

func (x Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_persqueue_proto_enumTypes[0].Descriptor()
}

func (Codec) Type() protoreflect.EnumType {
	return &file_persqueue_proto_enumTypes[0]
}

func (x Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Codec.Descriptor instead.
func (Codec) EnumDescriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{0}
}

type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_persqueue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MigrationStreamingReadClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logbroker requires credentials to precede the request on the wire.
	Token []byte `protobuf:"bytes,20,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*MigrationStreamingReadClientMessage_InitRequest
	//	*MigrationStreamingReadClientMessage_Read
	//	*MigrationStreamingReadClientMessage_StartRead
	//	*MigrationStreamingReadClientMessage_Commit
	//	*MigrationStreamingReadClientMessage_Released
	//	*MigrationStreamingReadClientMessage_Status
	Request       isMigrationStreamingReadClientMessage_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStreamingReadClientMessage) Reset() {
	*x = MigrationStreamingReadClientMessage{}
	mi := &file_persqueue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStreamingReadClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStreamingReadClientMessage) ProtoMessage() {}

func (x *MigrationStreamingReadClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStreamingReadClientMessage.ProtoReflect.Descriptor instead.
func (*MigrationStreamingReadClientMessage) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationStreamingReadClientMessage) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetRequest() isMigrationStreamingReadClientMessage_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetInitRequest() *InitRequest {
	if x != nil {
		if x, ok := x.Request.(*MigrationStreamingReadClientMessage_InitRequest); ok {
			return x.InitRequest
		}
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetRead() *Read {
	if x != nil {
		if x, ok := x.Request.(*MigrationStreamingReadClientMessage_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetStartRead() *StartRead {
	if x != nil {
		if x, ok := x.Request.(*MigrationStreamingReadClientMessage_StartRead); ok {
			return x.StartRead
		}
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetCommit() *Commit {
	if x != nil {
		if x, ok := x.Request.(*MigrationStreamingReadClientMessage_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetReleased() *Released {
	if x != nil {
		if x, ok := x.Request.(*MigrationStreamingReadClientMessage_Released); ok {
			return x.Released
		}
	}
	return nil
}

func (x *MigrationStreamingReadClientMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Request.(*MigrationStreamingReadClientMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isMigrationStreamingReadClientMessage_Request interface {
	isMigrationStreamingReadClientMessage_Request()
}

type MigrationStreamingReadClientMessage_InitRequest struct {
	InitRequest *InitRequest `protobuf:"bytes,1,opt,name=init_request,json=initRequest,proto3,oneof"`
}

type MigrationStreamingReadClientMessage_Read struct {
	Read *Read `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type MigrationStreamingReadClientMessage_StartRead struct {
	StartRead *StartRead `protobuf:"bytes,3,opt,name=start_read,json=startRead,proto3,oneof"`
}

type MigrationStreamingReadClientMessage_Commit struct {
	Commit *Commit `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type MigrationStreamingReadClientMessage_Released struct {
	Released *Released `protobuf:"bytes,5,opt,name=released,proto3,oneof"`
}

type MigrationStreamingReadClientMessage_Status struct {
	Status *Status `protobuf:"bytes,6,opt,name=status,proto3,oneof"`
}

func (*MigrationStreamingReadClientMessage_InitRequest) isMigrationStreamingReadClientMessage_Request() {
}

func (*MigrationStreamingReadClientMessage_Read) isMigrationStreamingReadClientMessage_Request() {}

func (*MigrationStreamingReadClientMessage_StartRead) isMigrationStreamingReadClientMessage_Request() {
}

func (*MigrationStreamingReadClientMessage_Commit) isMigrationStreamingReadClientMessage_Request() {}

func (*MigrationStreamingReadClientMessage_Released) isMigrationStreamingReadClientMessage_Request() {
}

func (*MigrationStreamingReadClientMessage_Status) isMigrationStreamingReadClientMessage_Request() {}

type TopicReadSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Topic                string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionGroupIds    []int64                `protobuf:"varint,2,rep,packed,name=partition_group_ids,json=partitionGroupIds,proto3" json:"partition_group_ids,omitempty"`
	StartFromWrittenAtMs int64                  `protobuf:"varint,3,opt,name=start_from_written_at_ms,json=startFromWrittenAtMs,proto3" json:"start_from_written_at_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TopicReadSettings) Reset() {
	*x = TopicReadSettings{}
	mi := &file_persqueue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicReadSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicReadSettings) ProtoMessage() {}

func (x *TopicReadSettings) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicReadSettings.ProtoReflect.Descriptor instead.
func (*TopicReadSettings) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{2}
}

func (x *TopicReadSettings) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicReadSettings) GetPartitionGroupIds() []int64 {
	if x != nil {
		return x.PartitionGroupIds
	}
	return nil
}

func (x *TopicReadSettings) GetStartFromWrittenAtMs() int64 {
	if x != nil {
		return x.StartFromWrittenAtMs
	}
	return 0
}

type ReadParams struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxReadMessagesCount uint32                 `protobuf:"varint,1,opt,name=max_read_messages_count,json=maxReadMessagesCount,proto3" json:"max_read_messages_count,omitempty"`
	MaxReadSize          uint32                 `protobuf:"varint,2,opt,name=max_read_size,json=maxReadSize,proto3" json:"max_read_size,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReadParams) Reset() {
	*x = ReadParams{}
	mi := &file_persqueue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadParams) ProtoMessage() {}

func (x *ReadParams) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadParams.ProtoReflect.Descriptor instead.
func (*ReadParams) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{3}
}

func (x *ReadParams) GetMaxReadMessagesCount() uint32 {
	if x != nil {
		return x.MaxReadMessagesCount
	}
	return 0
}

func (x *ReadParams) GetMaxReadSize() uint32 {
	if x != nil {
		return x.MaxReadSize
	}
	return 0
}

type InitRequest struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	TopicsReadSettings             []*TopicReadSettings   `protobuf:"bytes,1,rep,name=topics_read_settings,json=topicsReadSettings,proto3" json:"topics_read_settings,omitempty"`
	ReadOnlyOriginal               bool                   `protobuf:"varint,2,opt,name=read_only_original,json=readOnlyOriginal,proto3" json:"read_only_original,omitempty"`
	Consumer                       string                 `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	MaxLagDurationMs               int64                  `protobuf:"varint,4,opt,name=max_lag_duration_ms,json=maxLagDurationMs,proto3" json:"max_lag_duration_ms,omitempty"`
	StartFromWrittenAtMs           int64                  `protobuf:"varint,5,opt,name=start_from_written_at_ms,json=startFromWrittenAtMs,proto3" json:"start_from_written_at_ms,omitempty"`
	MaxSupportedBlockFormatVersion int64                  `protobuf:"varint,6,opt,name=max_supported_block_format_version,json=maxSupportedBlockFormatVersion,proto3" json:"max_supported_block_format_version,omitempty"`
	MaxMetaCacheSize               int64                  `protobuf:"varint,10,opt,name=max_meta_cache_size,json=maxMetaCacheSize,proto3" json:"max_meta_cache_size,omitempty"`
	ReadParams                     *ReadParams            `protobuf:"bytes,42,opt,name=read_params,json=readParams,proto3" json:"read_params,omitempty"`
	SessionId                      string                 `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnectionAttempt              int64                  `protobuf:"varint,101,opt,name=connection_attempt,json=connectionAttempt,proto3" json:"connection_attempt,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_persqueue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{4}
}

func (x *InitRequest) GetTopicsReadSettings() []*TopicReadSettings {
	if x != nil {
		return x.TopicsReadSettings
	}
	return nil
}

func (x *InitRequest) GetReadOnlyOriginal() bool {
	if x != nil {
		return x.ReadOnlyOriginal
	}
	return false
}

func (x *InitRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *InitRequest) GetMaxLagDurationMs() int64 {
	if x != nil {
		return x.MaxLagDurationMs
	}
	return 0
}

func (x *InitRequest) GetStartFromWrittenAtMs() int64 {
	if x != nil {
		return x.StartFromWrittenAtMs
	}
	return 0
}

func (x *InitRequest) GetMaxSupportedBlockFormatVersion() int64 {
	if x != nil {
		return x.MaxSupportedBlockFormatVersion
	}
	return 0
}

func (x *InitRequest) GetMaxMetaCacheSize() int64 {
	if x != nil {
		return x.MaxMetaCacheSize
	}
	return 0
}

func (x *InitRequest) GetReadParams() *ReadParams {
	if x != nil {
		return x.ReadParams
	}
	return nil
}

func (x *InitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitRequest) GetConnectionAttempt() int64 {
	if x != nil {
		return x.ConnectionAttempt
	}
	return 0
}

type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_persqueue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{5}
}

type StartRead struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster          string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition        uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	AssignId         uint64                 `protobuf:"varint,5,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	ReadOffset       uint64                 `protobuf:"varint,6,opt,name=read_offset,json=readOffset,proto3" json:"read_offset,omitempty"`
	CommitOffset     uint64                 `protobuf:"varint,7,opt,name=commit_offset,json=commitOffset,proto3" json:"commit_offset,omitempty"`
	VerifyReadOffset bool                   `protobuf:"varint,8,opt,name=verify_read_offset,json=verifyReadOffset,proto3" json:"verify_read_offset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartRead) Reset() {
	*x = StartRead{}
	mi := &file_persqueue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRead) ProtoMessage() {}

func (x *StartRead) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRead.ProtoReflect.Descriptor instead.
func (*StartRead) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{6}
}

func (x *StartRead) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *StartRead) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *StartRead) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *StartRead) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *StartRead) GetReadOffset() uint64 {
	if x != nil {
		return x.ReadOffset
	}
	return 0
}

func (x *StartRead) GetCommitOffset() uint64 {
	if x != nil {
		return x.CommitOffset
	}
	return 0
}

func (x *StartRead) GetVerifyReadOffset() bool {
	if x != nil {
		return x.VerifyReadOffset
	}
	return false
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       []*CommitCookie        `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty"`
	OffsetRanges  []*OffsetRange         `protobuf:"bytes,2,rep,name=offset_ranges,json=offsetRanges,proto3" json:"offset_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_persqueue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{7}
}

func (x *Commit) GetCookies() []*CommitCookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *Commit) GetOffsetRanges() []*OffsetRange {
	if x != nil {
		return x.OffsetRanges
	}
	return nil
}

type CommitCookie struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssignId        uint64                 `protobuf:"varint,1,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	PartitionCookie uint64                 `protobuf:"varint,2,opt,name=partition_cookie,json=partitionCookie,proto3" json:"partition_cookie,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommitCookie) Reset() {
	*x = CommitCookie{}
	mi := &file_persqueue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCookie) ProtoMessage() {}

func (x *CommitCookie) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCookie.ProtoReflect.Descriptor instead.
func (*CommitCookie) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{8}
}

func (x *CommitCookie) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *CommitCookie) GetPartitionCookie() uint64 {
	if x != nil {
		return x.PartitionCookie
	}
	return 0
}

type OffsetRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignId      uint64                 `protobuf:"varint,1,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	StartOffset   uint64                 `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     uint64                 `protobuf:"varint,3,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffsetRange) Reset() {
	*x = OffsetRange{}
	mi := &file_persqueue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffsetRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffsetRange) ProtoMessage() {}

func (x *OffsetRange) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffsetRange.ProtoReflect.Descriptor instead.
func (*OffsetRange) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{9}
}

func (x *OffsetRange) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *OffsetRange) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *OffsetRange) GetEndOffset() uint64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

type Released struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition     uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	AssignId      uint64                 `protobuf:"varint,5,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Released) Reset() {
	*x = Released{}
	mi := &file_persqueue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Released) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Released) ProtoMessage() {}

func (x *Released) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Released.ProtoReflect.Descriptor instead.
func (*Released) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{10}
}

func (x *Released) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Released) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Released) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Released) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition     uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	AssignId      uint64                 `protobuf:"varint,5,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_persqueue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{11}
}

func (x *Status) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Status) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Status) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Status) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

type MigrationStreamingReadServerMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Issues []*IssueMessage        `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*MigrationStreamingReadServerMessage_InitResponse
	//	*MigrationStreamingReadServerMessage_DataBatch
	//	*MigrationStreamingReadServerMessage_Assigned
	//	*MigrationStreamingReadServerMessage_Release
	//	*MigrationStreamingReadServerMessage_Committed
	//	*MigrationStreamingReadServerMessage_PartitionStatus
	Response      isMigrationStreamingReadServerMessage_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationStreamingReadServerMessage) Reset() {
	*x = MigrationStreamingReadServerMessage{}
	mi := &file_persqueue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStreamingReadServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStreamingReadServerMessage) ProtoMessage() {}

func (x *MigrationStreamingReadServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStreamingReadServerMessage.ProtoReflect.Descriptor instead.
func (*MigrationStreamingReadServerMessage) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{12}
}

func (x *MigrationStreamingReadServerMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MigrationStreamingReadServerMessage) GetIssues() []*IssueMessage {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetResponse() isMigrationStreamingReadServerMessage_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetInitResponse() *InitResponse {
	if x != nil {
		if x, ok := x.Response.(*MigrationStreamingReadServerMessage_InitResponse); ok {
			return x.InitResponse
		}
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetDataBatch() *DataBatch {
	if x != nil {
		if x, ok := x.Response.(*MigrationStreamingReadServerMessage_DataBatch); ok {
			return x.DataBatch
		}
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetAssigned() *Assigned {
	if x != nil {
		if x, ok := x.Response.(*MigrationStreamingReadServerMessage_Assigned); ok {
			return x.Assigned
		}
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetRelease() *Release {
	if x != nil {
		if x, ok := x.Response.(*MigrationStreamingReadServerMessage_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetCommitted() *Committed {
	if x != nil {
		if x, ok := x.Response.(*MigrationStreamingReadServerMessage_Committed); ok {
			return x.Committed
		}
	}
	return nil
}

func (x *MigrationStreamingReadServerMessage) GetPartitionStatus() *PartitionStatus {
	if x != nil {
		if x, ok := x.Response.(*MigrationStreamingReadServerMessage_PartitionStatus); ok {
			return x.PartitionStatus
		}
	}
	return nil
}

type isMigrationStreamingReadServerMessage_Response interface {
	isMigrationStreamingReadServerMessage_Response()
}

type MigrationStreamingReadServerMessage_InitResponse struct {
	InitResponse *InitResponse `protobuf:"bytes,3,opt,name=init_response,json=initResponse,proto3,oneof"`
}

type MigrationStreamingReadServerMessage_DataBatch struct {
	DataBatch *DataBatch `protobuf:"bytes,4,opt,name=data_batch,json=dataBatch,proto3,oneof"`
}

type MigrationStreamingReadServerMessage_Assigned struct {
	Assigned *Assigned `protobuf:"bytes,5,opt,name=assigned,proto3,oneof"`
}

type MigrationStreamingReadServerMessage_Release struct {
	Release *Release `protobuf:"bytes,6,opt,name=release,proto3,oneof"`
}

type MigrationStreamingReadServerMessage_Committed struct {
	Committed *Committed `protobuf:"bytes,7,opt,name=committed,proto3,oneof"`
}

type MigrationStreamingReadServerMessage_PartitionStatus struct {
	PartitionStatus *PartitionStatus `protobuf:"bytes,8,opt,name=partition_status,json=partitionStatus,proto3,oneof"`
}

func (*MigrationStreamingReadServerMessage_InitResponse) isMigrationStreamingReadServerMessage_Response() {
}

func (*MigrationStreamingReadServerMessage_DataBatch) isMigrationStreamingReadServerMessage_Response() {
}

func (*MigrationStreamingReadServerMessage_Assigned) isMigrationStreamingReadServerMessage_Response() {
}

func (*MigrationStreamingReadServerMessage_Release) isMigrationStreamingReadServerMessage_Response() {
}

func (*MigrationStreamingReadServerMessage_Committed) isMigrationStreamingReadServerMessage_Response() {
}

func (*MigrationStreamingReadServerMessage_PartitionStatus) isMigrationStreamingReadServerMessage_Response() {
}

type IssueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueCode     uint32                 `protobuf:"varint,1,opt,name=issue_code,json=issueCode,proto3" json:"issue_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMessage) Reset() {
	*x = IssueMessage{}
	mi := &file_persqueue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMessage) ProtoMessage() {}

func (x *IssueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMessage.ProtoReflect.Descriptor instead.
func (*IssueMessage) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{13}
}

func (x *IssueMessage) GetIssueCode() uint32 {
	if x != nil {
		return x.IssueCode
	}
	return 0
}

func (x *IssueMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SessionId                 string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BlockFormatVersionByTopic map[string]int64       `protobuf:"bytes,2,rep,name=block_format_version_by_topic,json=blockFormatVersionByTopic,proto3" json:"block_format_version_by_topic,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MaxMetaCacheSize          int64                  `protobuf:"varint,10,opt,name=max_meta_cache_size,json=maxMetaCacheSize,proto3" json:"max_meta_cache_size,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_persqueue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{14}
}

func (x *InitResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitResponse) GetBlockFormatVersionByTopic() map[string]int64 {
	if x != nil {
		return x.BlockFormatVersionByTopic
	}
	return nil
}

func (x *InitResponse) GetMaxMetaCacheSize() int64 {
	if x != nil {
		return x.MaxMetaCacheSize
	}
	return 0
}

type Assigned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition     uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	AssignId      uint64                 `protobuf:"varint,5,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	ReadOffset    uint64                 `protobuf:"varint,6,opt,name=read_offset,json=readOffset,proto3" json:"read_offset,omitempty"`
	EndOffset     uint64                 `protobuf:"varint,7,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assigned) Reset() {
	*x = Assigned{}
	mi := &file_persqueue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assigned) ProtoMessage() {}

func (x *Assigned) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assigned.ProtoReflect.Descriptor instead.
func (*Assigned) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{15}
}

func (x *Assigned) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Assigned) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Assigned) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Assigned) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *Assigned) GetReadOffset() uint64 {
	if x != nil {
		return x.ReadOffset
	}
	return 0
}

func (x *Assigned) GetEndOffset() uint64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

type Release struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster         string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition       uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	AssignId        uint64                 `protobuf:"varint,5,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	ForcefulRelease bool                   `protobuf:"varint,6,opt,name=forceful_release,json=forcefulRelease,proto3" json:"forceful_release,omitempty"`
	CommitOffset    uint64                 `protobuf:"varint,7,opt,name=commit_offset,json=commitOffset,proto3" json:"commit_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_persqueue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{16}
}

func (x *Release) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Release) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Release) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Release) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *Release) GetForcefulRelease() bool {
	if x != nil {
		return x.ForcefulRelease
	}
	return false
}

func (x *Release) GetCommitOffset() uint64 {
	if x != nil {
		return x.CommitOffset
	}
	return 0
}

type Committed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookies       []*CommitCookie        `protobuf:"bytes,1,rep,name=cookies,proto3" json:"cookies,omitempty"`
	OffsetRanges  []*OffsetRange         `protobuf:"bytes,2,rep,name=offset_ranges,json=offsetRanges,proto3" json:"offset_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Committed) Reset() {
	*x = Committed{}
	mi := &file_persqueue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Committed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Committed) ProtoMessage() {}

func (x *Committed) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Committed.ProtoReflect.Descriptor instead.
func (*Committed) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{17}
}

func (x *Committed) GetCookies() []*CommitCookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *Committed) GetOffsetRanges() []*OffsetRange {
	if x != nil {
		return x.OffsetRanges
	}
	return nil
}

type PartitionStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster          string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition        uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	AssignId         uint64                 `protobuf:"varint,5,opt,name=assign_id,json=assignId,proto3" json:"assign_id,omitempty"`
	CommittedOffset  uint64                 `protobuf:"varint,6,opt,name=committed_offset,json=committedOffset,proto3" json:"committed_offset,omitempty"`
	EndOffset        uint64                 `protobuf:"varint,7,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	WriteWatermarkMs uint64                 `protobuf:"varint,8,opt,name=write_watermark_ms,json=writeWatermarkMs,proto3" json:"write_watermark_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PartitionStatus) Reset() {
	*x = PartitionStatus{}
	mi := &file_persqueue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionStatus) ProtoMessage() {}

func (x *PartitionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionStatus.ProtoReflect.Descriptor instead.
func (*PartitionStatus) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{18}
}

func (x *PartitionStatus) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *PartitionStatus) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *PartitionStatus) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionStatus) GetAssignId() uint64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *PartitionStatus) GetCommittedOffset() uint64 {
	if x != nil {
		return x.CommittedOffset
	}
	return 0
}

func (x *PartitionStatus) GetEndOffset() uint64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *PartitionStatus) GetWriteWatermarkMs() uint64 {
	if x != nil {
		return x.WriteWatermarkMs
	}
	return 0
}

type DataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionData []*PartitionData       `protobuf:"bytes,1,rep,name=partition_data,json=partitionData,proto3" json:"partition_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_persqueue_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{19}
}

func (x *DataBatch) GetPartitionData() []*PartitionData {
	if x != nil {
		return x.PartitionData
	}
	return nil
}

type PartitionData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           *Path                  `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cluster         string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Partition       uint64                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Batches         []*Batch               `protobuf:"bytes,4,rep,name=batches,proto3" json:"batches,omitempty"`
	Cookie          *CommitCookie          `protobuf:"bytes,5,opt,name=cookie,proto3" json:"cookie,omitempty"`
	DeprecatedTopic string                 `protobuf:"bytes,10,opt,name=deprecated_topic,json=deprecatedTopic,proto3" json:"deprecated_topic,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartitionData) Reset() {
	*x = PartitionData{}
	mi := &file_persqueue_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionData) ProtoMessage() {}

func (x *PartitionData) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionData.ProtoReflect.Descriptor instead.
func (*PartitionData) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{20}
}

func (x *PartitionData) GetTopic() *Path {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *PartitionData) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *PartitionData) GetPartition() uint64 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionData) GetBatches() []*Batch {
	if x != nil {
		return x.Batches
	}
	return nil
}

func (x *PartitionData) GetCookie() *CommitCookie {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *PartitionData) GetDeprecatedTopic() string {
	if x != nil {
		return x.DeprecatedTopic
	}
	return ""
}

type Batch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageData      []*MessageData         `protobuf:"bytes,1,rep,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	SourceId         []byte                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ExtraFields      []*KeyValue            `protobuf:"bytes,3,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	WriteTimestampMs uint64                 `protobuf:"varint,4,opt,name=write_timestamp_ms,json=writeTimestampMs,proto3" json:"write_timestamp_ms,omitempty"`
	Ip               string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_persqueue_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{21}
}

func (x *Batch) GetMessageData() []*MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *Batch) GetSourceId() []byte {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *Batch) GetExtraFields() []*KeyValue {
	if x != nil {
		return x.ExtraFields
	}
	return nil
}

func (x *Batch) GetWriteTimestampMs() uint64 {
	if x != nil {
		return x.WriteTimestampMs
	}
	return 0
}

func (x *Batch) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type MessageData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Offset            uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	SeqNo             uint64                 `protobuf:"varint,2,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	CreateTimestampMs uint64                 `protobuf:"varint,3,opt,name=create_timestamp_ms,json=createTimestampMs,proto3" json:"create_timestamp_ms,omitempty"`
	Codec             Codec                  `protobuf:"varint,4,opt,name=codec,proto3,enum=Ydb.PersQueue.V1.Codec" json:"codec,omitempty"`
	Data              []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	UncompressedSize  uint64                 `protobuf:"varint,6,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
	PartitionKey      string                 `protobuf:"bytes,7,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	ExplicitHash      []byte                 `protobuf:"bytes,8,opt,name=explicit_hash,json=explicitHash,proto3" json:"explicit_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	mi := &file_persqueue_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{22}
}

func (x *MessageData) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MessageData) GetSeqNo() uint64 {
	if x != nil {
		return x.SeqNo
	}
	return 0
}

func (x *MessageData) GetCreateTimestampMs() uint64 {
	if x != nil {
		return x.CreateTimestampMs
	}
	return 0
}

func (x *MessageData) GetCodec() Codec {
	if x != nil {
		return x.Codec
	}
	return Codec_CODEC_UNSPECIFIED
}

func (x *MessageData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MessageData) GetUncompressedSize() uint64 {
	if x != nil {
		return x.UncompressedSize
	}
	return 0
}

func (x *MessageData) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *MessageData) GetExplicitHash() []byte {
	if x != nil {
		return x.ExplicitHash
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_persqueue_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_persqueue_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_persqueue_proto_rawDescGZIP(), []int{23}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_persqueue_proto protoreflect.FileDescriptor

const file_persqueue_proto_rawDesc = "" +
	"\n" +
	"\x0fpersqueue.proto\x12\x10Ydb.PersQueue.V1\"\x1a\n" +
	"\x04Path\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x98\x03\n" +
	"#MigrationStreamingReadClientMessage\x12\x14\n" +
	"\x05token\x18\x14 \x01(\fR\x05token\x12B\n" +
	"\finit_request\x18\x01 \x01(\v2\x1d.Ydb.PersQueue.V1.InitRequestH\x00R\vinitRequest\x12,\n" +
	"\x04read\x18\x02 \x01(\v2\x16.Ydb.PersQueue.V1.ReadH\x00R\x04read\x12<\n" +
	"\n" +
	"start_read\x18\x03 \x01(\v2\x1b.Ydb.PersQueue.V1.StartReadH\x00R\tstartRead\x122\n" +
	"\x06commit\x18\x04 \x01(\v2\x18.Ydb.PersQueue.V1.CommitH\x00R\x06commit\x128\n" +
	"\breleased\x18\x05 \x01(\v2\x1a.Ydb.PersQueue.V1.ReleasedH\x00R\breleased\x122\n" +
	"\x06status\x18\x06 \x01(\v2\x18.Ydb.PersQueue.V1.StatusH\x00R\x06statusB\t\n" +
	"\arequest\"\x91\x01\n" +
	"\x11TopicReadSettings\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12.\n" +
	"\x13partition_group_ids\x18\x02 \x03(\x03R\x11partitionGroupIds\x126\n" +
	"\x18start_from_written_at_ms\x18\x03 \x01(\x03R\x14startFromWrittenAtMs\"g\n" +
	"\n" +
	"ReadParams\x125\n" +
	"\x17max_read_messages_count\x18\x01 \x01(\rR\x14maxReadMessagesCount\x12\"\n" +
	"\rmax_read_size\x18\x02 \x01(\rR\vmaxReadSize\"\x9d\x04\n" +
	"\vInitRequest\x12U\n" +
	"\x14topics_read_settings\x18\x01 \x03(\v2#.Ydb.PersQueue.V1.TopicReadSettingsR\x12topicsReadSettings\x12,\n" +
	"\x12read_only_original\x18\x02 \x01(\bR\x10readOnlyOriginal\x12\x1a\n" +
	"\bconsumer\x18\x03 \x01(\tR\bconsumer\x12-\n" +
	"\x13max_lag_duration_ms\x18\x04 \x01(\x03R\x10maxLagDurationMs\x126\n" +
	"\x18start_from_written_at_ms\x18\x05 \x01(\x03R\x14startFromWrittenAtMs\x12J\n" +
	"\"max_supported_block_format_version\x18\x06 \x01(\x03R\x1emaxSupportedBlockFormatVersion\x12-\n" +
	"\x13max_meta_cache_size\x18\n" +
	" \x01(\x03R\x10maxMetaCacheSize\x12=\n" +
	"\vread_params\x18* \x01(\v2\x1c.Ydb.PersQueue.V1.ReadParamsR\n" +
	"readParams\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\x12-\n" +
	"\x12connection_attempt\x18e \x01(\x03R\x11connectionAttempt\"\x06\n" +
	"\x04Read\"\x82\x02\n" +
	"\tStartRead\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x12\x1b\n" +
	"\tassign_id\x18\x05 \x01(\x04R\bassignId\x12\x1f\n" +
	"\vread_offset\x18\x06 \x01(\x04R\n" +
	"readOffset\x12#\n" +
	"\rcommit_offset\x18\a \x01(\x04R\fcommitOffset\x12,\n" +
	"\x12verify_read_offset\x18\b \x01(\bR\x10verifyReadOffset\"\x86\x01\n" +
	"\x06Commit\x128\n" +
	"\acookies\x18\x01 \x03(\v2\x1e.Ydb.PersQueue.V1.CommitCookieR\acookies\x12B\n" +
	"\roffset_ranges\x18\x02 \x03(\v2\x1d.Ydb.PersQueue.V1.OffsetRangeR\foffsetRanges\"V\n" +
	"\fCommitCookie\x12\x1b\n" +
	"\tassign_id\x18\x01 \x01(\x04R\bassignId\x12)\n" +
	"\x10partition_cookie\x18\x02 \x01(\x04R\x0fpartitionCookie\"l\n" +
	"\vOffsetRange\x12\x1b\n" +
	"\tassign_id\x18\x01 \x01(\x04R\bassignId\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x04R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x03 \x01(\x04R\tendOffset\"\x8d\x01\n" +
	"\bReleased\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x12\x1b\n" +
	"\tassign_id\x18\x05 \x01(\x04R\bassignId\"\x8b\x01\n" +
	"\x06Status\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x12\x1b\n" +
	"\tassign_id\x18\x05 \x01(\x04R\bassignId\"\x84\x04\n" +
	"#MigrationStreamingReadServerMessage\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x126\n" +
	"\x06issues\x18\x02 \x03(\v2\x1e.Ydb.PersQueue.V1.IssueMessageR\x06issues\x12E\n" +
	"\rinit_response\x18\x03 \x01(\v2\x1e.Ydb.PersQueue.V1.InitResponseH\x00R\finitResponse\x12<\n" +
	"\n" +
	"data_batch\x18\x04 \x01(\v2\x1b.Ydb.PersQueue.V1.DataBatchH\x00R\tdataBatch\x128\n" +
	"\bassigned\x18\x05 \x01(\v2\x1a.Ydb.PersQueue.V1.AssignedH\x00R\bassigned\x125\n" +
	"\arelease\x18\x06 \x01(\v2\x19.Ydb.PersQueue.V1.ReleaseH\x00R\arelease\x12;\n" +
	"\tcommitted\x18\a \x01(\v2\x1b.Ydb.PersQueue.V1.CommittedH\x00R\tcommitted\x12N\n" +
	"\x10partition_status\x18\b \x01(\v2!.Ydb.PersQueue.V1.PartitionStatusH\x00R\x0fpartitionStatusB\n" +
	"\n" +
	"\bresponse\"G\n" +
	"\fIssueMessage\x12\x1d\n" +
	"\n" +
	"issue_code\x18\x01 \x01(\rR\tissueCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x02\n" +
	"\fInitResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x7f\n" +
	"\x1dblock_format_version_by_topic\x18\x02 \x03(\v2=.Ydb.PersQueue.V1.InitResponse.BlockFormatVersionByTopicEntryR\x19blockFormatVersionByTopic\x12-\n" +
	"\x13max_meta_cache_size\x18\n" +
	" \x01(\x03R\x10maxMetaCacheSize\x1aL\n" +
	"\x1eBlockFormatVersionByTopicEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xcd\x01\n" +
	"\bAssigned\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x12\x1b\n" +
	"\tassign_id\x18\x05 \x01(\x04R\bassignId\x12\x1f\n" +
	"\vread_offset\x18\x06 \x01(\x04R\n" +
	"readOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\a \x01(\x04R\tendOffset\"\xdc\x01\n" +
	"\aRelease\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x12\x1b\n" +
	"\tassign_id\x18\x05 \x01(\x04R\bassignId\x12)\n" +
	"\x10forceful_release\x18\x06 \x01(\bR\x0fforcefulRelease\x12#\n" +
	"\rcommit_offset\x18\a \x01(\x04R\fcommitOffset\"\x89\x01\n" +
	"\tCommitted\x128\n" +
	"\acookies\x18\x01 \x03(\v2\x1e.Ydb.PersQueue.V1.CommitCookieR\acookies\x12B\n" +
	"\roffset_ranges\x18\x02 \x03(\v2\x1d.Ydb.PersQueue.V1.OffsetRangeR\foffsetRanges\"\x8c\x02\n" +
	"\x0fPartitionStatus\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x12\x1b\n" +
	"\tassign_id\x18\x05 \x01(\x04R\bassignId\x12)\n" +
	"\x10committed_offset\x18\x06 \x01(\x04R\x0fcommittedOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\a \x01(\x04R\tendOffset\x12,\n" +
	"\x12write_watermark_ms\x18\b \x01(\x04R\x10writeWatermarkMs\"S\n" +
	"\tDataBatch\x12F\n" +
	"\x0epartition_data\x18\x01 \x03(\v2\x1f.Ydb.PersQueue.V1.PartitionDataR\rpartitionData\"\x8b\x02\n" +
	"\rPartitionData\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.Ydb.PersQueue.V1.PathR\x05topic\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x04R\tpartition\x121\n" +
	"\abatches\x18\x04 \x03(\v2\x17.Ydb.PersQueue.V1.BatchR\abatches\x126\n" +
	"\x06cookie\x18\x05 \x01(\v2\x1e.Ydb.PersQueue.V1.CommitCookieR\x06cookie\x12)\n" +
	"\x10deprecated_topic\x18\n" +
	" \x01(\tR\x0fdeprecatedTopic\"\xe3\x01\n" +
	"\x05Batch\x12@\n" +
	"\fmessage_data\x18\x01 \x03(\v2\x1d.Ydb.PersQueue.V1.MessageDataR\vmessageData\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\fR\bsourceId\x12=\n" +
	"\fextra_fields\x18\x03 \x03(\v2\x1a.Ydb.PersQueue.V1.KeyValueR\vextraFields\x12,\n" +
	"\x12write_timestamp_ms\x18\x04 \x01(\x04R\x10writeTimestampMs\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\"\xa6\x02\n" +
	"\vMessageData\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x15\n" +
	"\x06seq_no\x18\x02 \x01(\x04R\x05seqNo\x12.\n" +
	"\x13create_timestamp_ms\x18\x03 \x01(\x04R\x11createTimestampMs\x12-\n" +
	"\x05codec\x18\x04 \x01(\x0e2\x17.Ydb.PersQueue.V1.CodecR\x05codec\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12+\n" +
	"\x11uncompressed_size\x18\x06 \x01(\x04R\x10uncompressedSize\x12#\n" +
	"\rpartition_key\x18\a \x01(\tR\fpartitionKey\x12#\n" +
	"\rexplicit_hash\x18\b \x01(\fR\fexplicitHash\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*]\n" +
	"\x05Codec\x12\x15\n" +
	"\x11CODEC_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCODEC_RAW\x10\x01\x12\x0e\n" +
	"\n" +
	"CODEC_GZIP\x10\x02\x12\x0e\n" +
	"\n" +
	"CODEC_LZOP\x10\x03\x12\x0e\n" +
	"\n" +
	"CODEC_ZSTD\x10\x042\x9f\x01\n" +
	"\x10PersQueueService\x12\x8a\x01\n" +
	"\x16MigrationStreamingRead\x125.Ydb.PersQueue.V1.MigrationStreamingReadClientMessage\x1a5.Ydb.PersQueue.V1.MigrationStreamingReadServerMessage(\x010\x01B)Z'transferia2-go/internal/pqproto;pqprotob\x06proto3"

var (
	file_persqueue_proto_rawDescOnce sync.Once
	file_persqueue_proto_rawDescData []byte
)

func file_persqueue_proto_rawDescGZIP() []byte {
	file_persqueue_proto_rawDescOnce.Do(func() {
		file_persqueue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_persqueue_proto_rawDesc), len(file_persqueue_proto_rawDesc)))
	})
	return file_persqueue_proto_rawDescData
}

var file_persqueue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_persqueue_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_persqueue_proto_goTypes = []any{
	(Codec)(0),   // 0: Ydb.PersQueue.V1.Codec
	(*Path)(nil), // 1: Ydb.PersQueue.V1.Path
	(*MigrationStreamingReadClientMessage)(nil), // 2: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage
	(*TopicReadSettings)(nil),                   // 3: Ydb.PersQueue.V1.TopicReadSettings
	(*ReadParams)(nil),                          // 4: Ydb.PersQueue.V1.ReadParams
	(*InitRequest)(nil),                         // 5: Ydb.PersQueue.V1.InitRequest
	(*Read)(nil),                                // 6: Ydb.PersQueue.V1.Read
	(*StartRead)(nil),                           // 7: Ydb.PersQueue.V1.StartRead
	(*Commit)(nil),                              // 8: Ydb.PersQueue.V1.Commit
	(*CommitCookie)(nil),                        // 9: Ydb.PersQueue.V1.CommitCookie
	(*OffsetRange)(nil),                         // 10: Ydb.PersQueue.V1.OffsetRange
	(*Released)(nil),                            // 11: Ydb.PersQueue.V1.Released
	(*Status)(nil),                              // 12: Ydb.PersQueue.V1.Status
	(*MigrationStreamingReadServerMessage)(nil), // 13: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage
	(*IssueMessage)(nil),                        // 14: Ydb.PersQueue.V1.IssueMessage
	(*InitResponse)(nil),                        // 15: Ydb.PersQueue.V1.InitResponse
	(*Assigned)(nil),                            // 16: Ydb.PersQueue.V1.Assigned
	(*Release)(nil),                             // 17: Ydb.PersQueue.V1.Release
	(*Committed)(nil),                           // 18: Ydb.PersQueue.V1.Committed
	(*PartitionStatus)(nil),                     // 19: Ydb.PersQueue.V1.PartitionStatus
	(*DataBatch)(nil),                           // 20: Ydb.PersQueue.V1.DataBatch
	(*PartitionData)(nil),                       // 21: Ydb.PersQueue.V1.PartitionData
	(*Batch)(nil),                               // 22: Ydb.PersQueue.V1.Batch
	(*MessageData)(nil),                         // 23: Ydb.PersQueue.V1.MessageData
	(*KeyValue)(nil),                            // 24: Ydb.PersQueue.V1.KeyValue
	nil,                                         // 25: Ydb.PersQueue.V1.InitResponse.BlockFormatVersionByTopicEntry
}
var file_persqueue_proto_depIdxs = []int32{
	5,  // 0: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage.init_request:type_name -> Ydb.PersQueue.V1.InitRequest
	6,  // 1: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage.read:type_name -> Ydb.PersQueue.V1.Read
	7,  // 2: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage.start_read:type_name -> Ydb.PersQueue.V1.StartRead
	8,  // 3: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage.commit:type_name -> Ydb.PersQueue.V1.Commit
	11, // 4: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage.released:type_name -> Ydb.PersQueue.V1.Released
	12, // 5: Ydb.PersQueue.V1.MigrationStreamingReadClientMessage.status:type_name -> Ydb.PersQueue.V1.Status
	3,  // 6: Ydb.PersQueue.V1.InitRequest.topics_read_settings:type_name -> Ydb.PersQueue.V1.TopicReadSettings
	4,  // 7: Ydb.PersQueue.V1.InitRequest.read_params:type_name -> Ydb.PersQueue.V1.ReadParams
	1,  // 8: Ydb.PersQueue.V1.StartRead.topic:type_name -> Ydb.PersQueue.V1.Path
	9,  // 9: Ydb.PersQueue.V1.Commit.cookies:type_name -> Ydb.PersQueue.V1.CommitCookie
	10, // 10: Ydb.PersQueue.V1.Commit.offset_ranges:type_name -> Ydb.PersQueue.V1.OffsetRange
	1,  // 11: Ydb.PersQueue.V1.Released.topic:type_name -> Ydb.PersQueue.V1.Path
	1,  // 12: Ydb.PersQueue.V1.Status.topic:type_name -> Ydb.PersQueue.V1.Path
	14, // 13: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.issues:type_name -> Ydb.PersQueue.V1.IssueMessage
	15, // 14: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.init_response:type_name -> Ydb.PersQueue.V1.InitResponse
	20, // 15: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.data_batch:type_name -> Ydb.PersQueue.V1.DataBatch
	16, // 16: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.assigned:type_name -> Ydb.PersQueue.V1.Assigned
	17, // 17: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.release:type_name -> Ydb.PersQueue.V1.Release
	18, // 18: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.committed:type_name -> Ydb.PersQueue.V1.Committed
	19, // 19: Ydb.PersQueue.V1.MigrationStreamingReadServerMessage.partition_status:type_name -> Ydb.PersQueue.V1.PartitionStatus
	25, // 20: Ydb.PersQueue.V1.InitResponse.block_format_version_by_topic:type_name -> Ydb.PersQueue.V1.InitResponse.BlockFormatVersionByTopicEntry
	1,  // 21: Ydb.PersQueue.V1.Assigned.topic:type_name -> Ydb.PersQueue.V1.Path
	1,  // 22: Ydb.PersQueue.V1.Release.topic:type_name -> Ydb.PersQueue.V1.Path
	9,  // 23: Ydb.PersQueue.V1.Committed.cookies:type_name -> Ydb.PersQueue.V1.CommitCookie
	10, // 24: Ydb.PersQueue.V1.Committed.offset_ranges:type_name -> Ydb.PersQueue.V1.OffsetRange
	1,  // 25: Ydb.PersQueue.V1.PartitionStatus.topic:type_name -> Ydb.PersQueue.V1.Path
	21, // 26: Ydb.PersQueue.V1.DataBatch.partition_data:type_name -> Ydb.PersQueue.V1.PartitionData
	1,  // 27: Ydb.PersQueue.V1.PartitionData.topic:type_name -> Ydb.PersQueue.V1.Path
	22, // 28: Ydb.PersQueue.V1.PartitionData.batches:type_name -> Ydb.PersQueue.V1.Batch
	9,  // 29: Ydb.PersQueue.V1.PartitionData.cookie:type_name -> Ydb.PersQueue.V1.CommitCookie
	23, // 30: Ydb.PersQueue.V1.Batch.message_data:type_name -> Ydb.PersQueue.V1.MessageData
	24, // 31: Ydb.PersQueue.V1.Batch.extra_fields:type_name -> Ydb.PersQueue.V1.KeyValue
	0,  // 32: Ydb.PersQueue.V1.MessageData.codec:type_name -> Ydb.PersQueue.V1.Codec
	2,  // 33: Ydb.PersQueue.V1.PersQueueService.MigrationStreamingRead:input_type -> Ydb.PersQueue.V1.MigrationStreamingReadClientMessage
	13, // 34: Ydb.PersQueue.V1.PersQueueService.MigrationStreamingRead:output_type -> Ydb.PersQueue.V1.MigrationStreamingReadServerMessage
	34, // [34:35] is the sub-list for method output_type
	33, // [33:34] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_persqueue_proto_init() }
func file_persqueue_proto_init() {
	if File_persqueue_proto != nil {
		return
	}
	file_persqueue_proto_msgTypes[1].OneofWrappers = []any{
		(*MigrationStreamingReadClientMessage_InitRequest)(nil),
		(*MigrationStreamingReadClientMessage_Read)(nil),
		(*MigrationStreamingReadClientMessage_StartRead)(nil),
		(*MigrationStreamingReadClientMessage_Commit)(nil),
		(*MigrationStreamingReadClientMessage_Released)(nil),
		(*MigrationStreamingReadClientMessage_Status)(nil),
	}
	file_persqueue_proto_msgTypes[12].OneofWrappers = []any{
		(*MigrationStreamingReadServerMessage_InitResponse)(nil),
		(*MigrationStreamingReadServerMessage_DataBatch)(nil),
		(*MigrationStreamingReadServerMessage_Assigned)(nil),
		(*MigrationStreamingReadServerMessage_Release)(nil),
		(*MigrationStreamingReadServerMessage_Committed)(nil),
		(*MigrationStreamingReadServerMessage_PartitionStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_persqueue_proto_rawDesc), len(file_persqueue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_persqueue_proto_goTypes,
		DependencyIndexes: file_persqueue_proto_depIdxs,
		EnumInfos:         file_persqueue_proto_enumTypes,
		MessageInfos:      file_persqueue_proto_msgTypes,
	}.Build()
	File_persqueue_proto = out.File
	file_persqueue_proto_goTypes = nil
	file_persqueue_proto_depIdxs = nil
}
