// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: persqueue.proto

package pqproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PersQueueService_MigrationStreamingRead_FullMethodName = "/Ydb.PersQueue.V1.PersQueueService/MigrationStreamingRead"
)

// PersQueueServiceClient is the client API for PersQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PersQueueServiceClient interface {
	MigrationStreamingRead(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage], error)
}

type persQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPersQueueServiceClient(cc grpc.ClientConnInterface) PersQueueServiceClient {
	return &persQueueServiceClient{cc}
}

func (c *persQueueServiceClient) MigrationStreamingRead(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PersQueueService_ServiceDesc.Streams[0], PersQueueService_MigrationStreamingRead_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersQueueService_MigrationStreamingReadClient = grpc.BidiStreamingClient[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage]

// PersQueueServiceServer is the server API for PersQueueService service.
// All implementations must embed UnimplementedPersQueueServiceServer
// for forward compatibility.
type PersQueueServiceServer interface {
	MigrationStreamingRead(grpc.BidiStreamingServer[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage]) error
	mustEmbedUnimplementedPersQueueServiceServer()
}

// UnimplementedPersQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPersQueueServiceServer struct{}

func (UnimplementedPersQueueServiceServer) MigrationStreamingRead(grpc.BidiStreamingServer[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage]) error {
	return status.Error(codes.Unimplemented, "method MigrationStreamingRead not implemented")
}
func (UnimplementedPersQueueServiceServer) mustEmbedUnimplementedPersQueueServiceServer() {}
func (UnimplementedPersQueueServiceServer) testEmbeddedByValue()                          {}

// UnsafePersQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PersQueueServiceServer will
// result in compilation errors.
type UnsafePersQueueServiceServer interface {
	mustEmbedUnimplementedPersQueueServiceServer()
}

func RegisterPersQueueServiceServer(s grpc.ServiceRegistrar, srv PersQueueServiceServer) {
	// If the following call panics, it indicates UnimplementedPersQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PersQueueService_ServiceDesc, srv)
}

func _PersQueueService_MigrationStreamingRead_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PersQueueServiceServer).MigrationStreamingRead(&grpc.GenericServerStream[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PersQueueService_MigrationStreamingReadServer = grpc.BidiStreamingServer[MigrationStreamingReadClientMessage, MigrationStreamingReadServerMessage]

// PersQueueService_ServiceDesc is the grpc.ServiceDesc for PersQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PersQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ydb.PersQueue.V1.PersQueueService",
	HandlerType: (*PersQueueServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MigrationStreamingRead",
			Handler:       _PersQueueService_MigrationStreamingRead_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "persqueue.proto",
}
